# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 4.1.0

app:
  image: mageinferno/magento2-nginx:1.9.14-0
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  ports:
    - 8000:80

appdata:
  image: tianon/true
  volumes:
    - /srv/www
    - ~/.composer:/var/www/.composer
    - ./www/app/code:/srv/www/app/code

phpfpm:
  image: mageinferno/magento2-nginx:1.9.14-0
  links:
    - db
  volumes_from:
    - appdata

db:
  image: mariadb:10.1.13
  volumes_from:
    - dbdata
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

rabbitmq:
  image: rabbitmq:3.5-management
  ports:
    - 15673:15672
    - 5672:5672

#setup:
#  image: virfaure/magento2-php
#  command: /usr/local/bin/mage-setup
#  links:
#    - db
#  volumes_from:
#    - appdata
#  environment:
#    - M2SETUP_DB_HOST=db
#    - M2SETUP_DB_NAME=magento2
#    - M2SETUP_DB_USER=magento2
#    - M2SETUP_DB_PASSWORD=magento2
#    - M2SETUP_BASE_URL=http://m2.localhost:8000/
#    - M2SETUP_ADMIN_FIRSTNAME=Admin
#    - M2SETUP_ADMIN_LASTNAME=User
#    - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
#    - M2SETUP_ADMIN_USER=magento2
#    - M2SETUP_ADMIN_PASSWORD=magento2
#    - M2SETUP_VERSION=2.0.5
#    - M2SETUP_USE_SAMPLE_DATA=false
#    - M2SETUP_USE_ARCHIVE=false
